value1=input("Please insert any value: ")
value2=input("Please insert another value: ")
print("Concatenation of your 2 values:",value1+value2)
print(" ")
Integer1=int(input("Please enter an integer: "))
Integer2=int(input("Please enter another integer: "))
sum1=print("Sum of your integers is",Integer1+Integer2)
print(" ")
decimal1=float(input("Please enter a decimal number: "))
decimal2=float(input("Please enter another decimal number: "))
sum2=print("Your decimal add up to:",decimal1+decimal2)
