'Wisani  Isaac Ngobeni__Student number_41819985'
Num1=float(input("Please insert 1st number: "))
Num2=float(input("Please insert 2nd number: "))
print("The sum of the two numbers is:",Num1+Num2)
print("The product of the two numbers is:",Num1*Num2)
print("The 1st number subtracted from 2nd number:",Num2-Num1)
print("The 1st number devided by 2nd number:",Num1/Num2)
print("The average of the two numbers is:",(Num1+Num2)/2)
print("The remainde of the devided numbers are:",Num1 % Num2)
print("The 2nd number to the power of the 1st is:",Num2**Num1)
